version: '3'
services:
  traefik:
    image: traefik:latest  # You can use the latest version
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"         # HTTP port
      - "443:443"       # HTTPS port
      - "8080:8080"     # Dashboard port
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/traefik:/etc/traefik"
      - "./letsencrypt:/letsencrypt"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik-dashboard.ayetu.net`)"
      - "traefik.http.routers.traefik.entrypoints=web,websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=production"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$2y$$05$$f2qE7YaiP0C2Ps4is0nP0ewFL7m9caGnUbWHV39d8lrM217fMw2di"
  go-scratch-app:
    image: go-scratch-app  # Replace with your actual Go app image
    container_name: go-scratch-app
    environment:
      - NAME=Umar
    networks:
      - web
    ports:
      - "8081:8080"  # Map internal Go app port 8080 to external port 8081
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.go-scratch-app.rule=Host(`traefik.ayetu.net`)"
      - "traefik.http.routers.go-scratch-app.entrypoints=web,websecure"
      - "traefik.http.routers.go-scratch-app.tls=true"
      - "traefik.http.routers.go-scratch-app.tls.certresolver=production"
  secrets-manager:
    image: secrets-manager  
    container_name: secrets-manager
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.secrets-manager.rule=Host(`secrets-manager.ayetu.net`)"
      - "traefik.http.routers.secrets-manager.entrypoints=web,websecure"
      - "traefik.http.routers.secrets-manager.tls=true"
      - "traefik.http.routers.secrets-manager.tls.certresolver=production"
networks:
  web:
    external: false
