version: '3'
volumes:
  traefik-ssl-certs:
    driver: local
services:
  traefik:
    image: traefik:v2.10  # You can use the latest version
    container_name: traefik
    ports:
      - "80:80"         # HTTP port
      - "443:443"       # HTTPS port
      - "8080:8080"     # Dashboard port
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/traefik:/etc/traefik"
      - "traefik-ssl-certs:/ssl-certs"
    networks:
      - web

networks:
  web:
    external: false
